In [40]:
from sklearn import tree
features = [[140,1], [130,1] ,[150,0] ,[170,0]]
labels = [0,0,1,1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(features, labels)
print (clf.predict([[150,0]]))
print (clf.predict([[160,1]]))

[1]
[0]


In [38]:
import numpy as np
from sklearn import tree
from sklearn.datasets import load_iris 
iris = load_iris()
print(iris.feature_names)
print(iris.target_names)
print (iris.data[0])

test_idx = [0,50,100]
train_target =np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis= 0)

test_target =iris.target[test_idx]
test_data =iris.data[test_idx]

clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

print(test_target)
print (clf.predict(test_data))

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[ 5.1  3.5  1.4  0.2]
[0 1 2]
[0 1 2]
